name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  install:
    name: Install node modules
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - run: pnpm install

  audit:
    name: Audit node modules
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm audit

  check:
    name: Check code quality
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm lint
        if: ${{ !cancelled() }}
      - run: pnpm format
        if: ${{ !cancelled() }}
      - run: pnpm lint:copyright
        if: ${{ !cancelled() }}
      - run: pnpm prettier
        if: ${{ !cancelled() }}

  build:
    name: Build test app
    needs: install
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm run build

  test:
    name: Run e2e tests
    needs: install
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-jammy

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - run: pnpm install
      - run: pnpm dlx playwright install --with-deps
      - run: pnpm run build
      - run: pnpm --filter=@itwin/test-app exec playwright test
        env:
          HOME: /root

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: apps/test-app/playwright-report/

  deploy-gh-pages:
    name: Deploy test app to github pages
    needs: install
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      BASE_FOLDER: ${{ github.event.number || github.ref_name != 'main' && github.ref_name || '' }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - run: pnpm install

      - name: Build test-app
        run: pnpm run build

      - name: List folders to preserve (open PRs)
        id: clean_exclude_folders
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            return [...((await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            })).data.map(pr => pr.number))].join('\n')

      - name: Deploy build output to gh-pages branch
        if: github.ref != 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ${{ github.workspace }}/apps/test-app/build/client
          target-folder: ${{ env.BASE_FOLDER }}
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com

      - name: Add deploy preview link under Checks
        if: github.ref != 'refs/heads/main' && always()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.event.pull_request.head.sha }}',
              state: 'success',
              context: 'Deploy preview',
              description: 'Live preview of the current branch',
              target_url: '${{ env.GH_PAGES_URL }}/${{ github.event.number }}/',
            })
